[package]
name = "Stegosaurus"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
secrecy = "0.10.3"
zeroize = "1.8.1"
rand_core = "0.9.3"
argon2 = "0.5.3"
hkdf = "0.12.4"
rand = "0.9.2"
sha2 = "0.10.9"